# Generated by Django 2.0.5 on 2018-05-03 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Venue', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(default=datetime.datetime(2018, 5, 3, 4, 54, 6, 412846, tzinfo=utc))),
            ],
        ),
    ]
