# Generated by Django 2.0.5 on 2018-05-03 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 4, 58, 26, 509674, tzinfo=utc)),
        ),
    ]
