# Generated by Django 2.0.5 on 2018-05-03 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0002_auto_20180503_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=20)),
                ('mailid', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 3, 5, 53, 51, 603795, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 5, 53, 51, 603201, tzinfo=utc)),
        ),
    ]
