# Generated by Django 2.0.5 on 2018-05-03 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0003_auto_20180503_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 6, 2, 50, 75705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 6, 2, 50, 76214, tzinfo=utc)),
        ),
    ]
