# Generated by Django 2.0.5 on 2018-05-03 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0004_auto_20180503_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=5)),
                ('product_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 6, 31, 49, 434372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 6, 31, 49, 434857, tzinfo=utc)),
        ),
    ]
