# Generated by Django 2.0.5 on 2018-05-03 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0005_auto_20180503_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 7, 7, 43, 721393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 7, 7, 43, 721872, tzinfo=utc)),
        ),
    ]
