# Generated by Django 2.0.5 on 2018-05-03 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0008_auto_20180503_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 13, 11, 1, 806401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 13, 11, 1, 806909, tzinfo=utc)),
        ),
    ]
