# Generated by Django 2.0.5 on 2018-05-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_comment_timesmow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='pool.Item'),
            preserve_default=False,
        ),
    ]
