# Generated by Django 2.0.5 on 2018-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_auto_20180507_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='event_description',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='event_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_images',
            field=models.ImageField(blank=True, null=True, upload_to='realapp/images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
