# Generated by Django 2.0.5 on 2018-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20180507_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_images',
            new_name='event_images',
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
