# Generated by Django 2.0.5 on 2018-05-15 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_auto_20180514_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
