# Generated by Django 2.0.5 on 2018-05-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_auto_20180507_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='book',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='country',
            new_name='venue',
        ),
    ]
