# Generated by Django 2.0.5 on 2018-05-15 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_item_creator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
