# Generated by Django 2.0.5 on 2018-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_auto_20180508_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detailed_images',
            field=models.ImageField(blank=True, null=True, upload_to='realapp/images'),
        ),
    ]
