# Generated by Django 2.0.5 on 2018-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_item_detailed_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
