# Generated by Django 2.0.5 on 2018-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
